import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";
import Authprovider from "@/provider/Authprovider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: {
    default: 'Car Doctor',
    template: '%s | Car Doctor'
  },
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cardoctorTheme">
      <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Circle-icons-car.svg/2048px-Circle-icons-car.svg.png" sizes="any" />
      <body className={`${geistSans.variable} ${geistMono.variable} max-w-[1300px] mx-auto`}>
        <Authprovider>
          <Navbar />
          {children}
          <Footer />
        </Authprovider>
      </body>
    </html>
  );
}
